#!/usr/bin/env perl

use Mojo::Base -strict;
use Toastr;

my $toastr = Toastr->new(
  channels => ['#toastr'],
  nick     => 'toastr',
  user     => 'toastr bot',
  server   => 'irc.perl.org:6667', 
);

$toastr->plugin('KarmaHandler');
$toastr->plugin('Toast');
$toastr->plugin('Hailo');
$toastr->start;

